//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace personal_pages
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public System.Guid ScheduleId { get; set; }
        public System.Guid CourseId { get; set; }
        public string TeacherId { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Class_Nr { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual User User { get; set; }
    }
}
